name: 'push'
description: 'Push to repo'
author: 'Mansi Ayer'
branding:
  icon: eye
  color: black
inputs:
  script:
    description: 'The path to the test-script to run, within the repository.'
    default: '.github/run-tests.sh'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
      - ${{ inputs.script }}




run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "42694815+${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "updating readme stars"
          git push 
