name: 'push'
description: 'pass a script to make changes and push to repo'
author: 'MansiAyer'
branding:
  icon: edit-3
  color: red
inputs:
  script:
    description: 'Script to make changes. Empty field will only push'
    required: false
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
    required: false
  actor:
    description: 'Owner username. For example, actions'
    default: ${{ github.actor }}
    required: false
  email:
    description: 'Email ID to be used for git config'
    required: true
secrets:
  actions_token:
      description: 'Actions secret token for authentication'
      default: ${{ secrets.GITHUB_TOKEN }}
      required: false
      #required: true
      
runs:
  using: 'ubuntu-latest'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
    
    - name: testing reuse workflow
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
        GITHUB_EMAIL: ${{ inputs.email }}
        GITHUB_ACTOR: ${{ inputs.actor }}
      runs: |
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}/
        python ${SCRIPT_PATH}
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${ACTOR_EMAIL}"
        git add .
        git commit -m "auto-updating repo"
        git push
      
    
        
    





