name: 'push'
description: 'pass a script to make changes and push to repo'
author: 'MansiAyer'
branding:
  icon: edit-3
  color: red
inputs:
  script:
    description: 'Script to make changes. Empty field will only push'
    required: false
  
      
runs:
  using: 'ubuntu-latest'
  steps:
    - name: test
      env:
        GITHUB_ACTOR: ${{ github.actor }}
      run: |
        echo ${GITHUB_EMAIL}
        echo ${GITHUB_ACTOR}
      
    
        
    





