name: 'push'
description: 'pass a script to make changes and push to repo'
author: 'MansiAyer'
branding:
  icon: edit-3
  color: red
inputs:
  script:
    description: 'Script to make changes. Empty field will only push'
    required: false
  actor:
    description: 'actor'
    required: false
    default: ${GITHUB_ACTOR}
  
      
jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: test
        env:
          GITHUB_ACTOR: ${{ inputs.actor }}
        run: |
          echo testing
          echo ${GITHUB_ACTOR}
      
    
        
    





